/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1e",
        "on-surface-variant": "#5b403f",
        "on-secondary-fixed-variant": "#81262a",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        surface: "#f7f9fb",
        "on-tertiary-container": "#f3fffc",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#00504a",
        "surface-variant": "#e0e3e5",
        primary: "#b7102a",
        "tertiary-fixed": "#8cf4e8",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#ffb3b1",
        "on-secondary-fixed": "#410007",
        "surface-container": "#eceef0",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed": "#ffdad8",
        "secondary-container": "#fd8584",
        "tertiary-container": "#008379",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary-container": "#db313f",
        "outline-variant": "#e4bebc",
        error: "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        background: "#f7f9fb",
        "inverse-primary": "#ffb3b1",
        "secondary-fixed-dim": "#ffb3b1",
        secondary: "#a03d40",
        "on-primary-fixed": "#410007",
        "on-secondary-container": "#741d22",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#00201d",
        "tertiary-fixed-dim": "#6fd8cc",
        "primary-fixed": "#ffdad8",
        tertiary: "#006860",
        outline: "#8f6f6e",
        "surface-tint": "#bb152c",
        "on-primary-fixed-variant": "#92001c",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Plus Jakarta Sans"],
        label: ["Plus Jakarta Sans"],
        sans: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
};

