export const demoBranches = [
  {
    id: 'demo-lto-marikina',
    name: 'LTO Marikina District Office',
    address: 'Marikina-Infanta Hwy, Brgy. Concepcion Uno, Marikina City',
    lat: 14.6508,
    lng: 121.1029,
    stats: {
      hasPlasticCards: true,
      avgWaitWalkIn: '1h 15m',
      avgWaitAppointment: '20m',
      grade: 'B',
      isPuno: false,
      highDemand: false,
      prequeueMinutes: 18,
      reportsToday: 146,
    },
  },
  {
    id: 'demo-lto-mandaluyong',
    name: 'LTO Mandaluyong Licensing Center',
    address: 'EDSA cor. Boni Ave, Mandaluyong City',
    lat: 14.5797,
    lng: 121.0473,
    stats: {
      hasPlasticCards: false,
      avgWaitWalkIn: '3h 05m',
      avgWaitAppointment: '55m',
      grade: 'D',
      isPuno: false,
      highDemand: true,
      prequeueMinutes: 42,
      reportsToday: 312,
    },
  },
  {
    id: 'demo-lto-santa-rosa',
    name: 'LTO Santa Rosa Licensing Center',
    address: 'National Hwy, Brgy. Balibago, Santa Rosa, Laguna',
    lat: 14.2946,
    lng: 121.1056,
    stats: {
      hasPlasticCards: true,
      avgWaitWalkIn: '2h 10m',
      avgWaitAppointment: '35m',
      grade: 'C',
      isPuno: true,
      highDemand: true,
      prequeueMinutes: 30,
      reportsToday: 228,
    },
  },
];

