// demoBranches.js — pre-seeded branches for Demo Mode
export const DEMO_BRANCHES = [
  {
    id: 'demo-1',
    name: 'LTO Diliman District',
    address: 'East Avenue, Quezon City',
    city: 'Quezon City, NCR',
    lat: 14.6507,
    lng: 121.0499,
    distanceKm: 3.2,
    operatingHours: '08:00–17:00',
    thumbnailUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAt5TLnAull670qLVuHpgUZVwqv2F2JqTBZ9sFCxYStOGjzeTLB2wM4rBrxgHhk0u-VE1GrivY06S3eb1g9h8_-lhLy_XRjPhiYSlc65Vbr6KmyYC8IMVaAyHS2CIkZ9Tu6PZxOR2Xd8u2GjFUQbb-rJ65al_IeeI9H7Kt3CDO2SvaqutsU9gFSxZ0rEspDSNFZA9jM8t6UiyP13yzdFP4T-pJAumZNyOoAJkaEVM15JGYA5oik_2d2GLXjzoHqfn903ObiZb85i3X7',
    hasPlasticCards: true,
    grade: 'C',
    reportsToday: 42,
    is_puno: false,
    hasActiveAnomaly: false,
    walkinAvgMinutes: 200,
    appointmentAvgMinutes: 45,
    prequeueMinutesBeforeOpen: 45,
    communityRequirements7d: [
      { tag: 'Updated MedCert', labelFil: 'Na-update na Medical Certificate', count: 12, status: 'missing' },
      { tag: 'Short bond only', labelFil: 'Short bond paper lamang', count: 5, status: 'ok' },
    ],
    high_demand_warning: false,
    intentDistancesKmLast15m: [],
    plastic_uncertain: false,
    historical_puno_risk: false,
    recentReports: [
      { id: 'dr1', queuePrefix: 'A', transactionType: 'License Renewal', waitMinutes: 215, isAnomaly: false, createdAt: Date.now() - 22 * 60 * 1000 },
      { id: 'dr2', queuePrefix: 'B', transactionType: 'MV Registration', waitMinutes: 180, isAnomaly: false, createdAt: Date.now() - 2 * 60 * 60 * 1000 },
    ],
  },
  {
    id: 'demo-2',
    name: 'QC Licensing Center',
    address: 'P. Tuazon Blvd, Cubao, QC',
    city: 'Quezon City, NCR',
    lat: 14.6195,
    lng: 121.0556,
    distanceKm: 5.1,
    operatingHours: '08:00–17:00',
    thumbnailUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDIVd2lrAYL1Qg54Pz7-Gt_TOD2GBPDKEIlDtl15TZEzlsW7sVg8EffwaNrQ-Uv7cS_mGrtChEILO-Siksfzkfm0FrUvUbi7j8CYMPV7-hYQxPi4ue_FPNgvNvMEj9kxIy0grVPAyj5ccUq0XegMJ0RH6G-kNM_D_OhMLMsDWrqulPE02c6MFePG_iymv38Ra69HV2wIJro8o6RTcyNYJh_XXSLGOUcGhyNlXI-EBkNmFsodhnj0N47lMbKQX6p3J520QdeyLJow7iG',
    hasPlasticCards: true,
    grade: 'B',
    reportsToday: 27,
    is_puno: false,
    hasActiveAnomaly: true,
    anomalyDescription: 'May biglaang system downtime na na-report sa cashier.',
    walkinAvgMinutes: 140,
    appointmentAvgMinutes: 30,
    prequeueMinutesBeforeOpen: 30,
    communityRequirements7d: [
      { tag: 'Extra photocopy', labelFil: 'Dagdag na photocopy ng OR/CR', count: 8, status: 'missing' },
      { tag: 'CDE Clearance', labelFil: 'CDE No Contact Clearance', count: 3, status: 'ok' },
    ],
    high_demand_warning: true,
    intentDistancesKmLast15m: [2.2, 2.0, 2.5, 2.1, 2.3, 2.4, 2.0, 2.6, 2.2, 2.1, 2.3, 2.4, 2.0, 2.6, 2.1, 2.2, 2.3, 2.4, 2.0, 2.5, 2.2, 2.1],
    plastic_uncertain: false,
    historical_puno_risk: false,
    recentReports: [
      { id: 'dr3', queuePrefix: 'Q', transactionType: 'License Renewal', waitMinutes: 150, isAnomaly: false, createdAt: Date.now() - 40 * 60 * 1000 },
      { id: 'dr4', queuePrefix: 'Q', transactionType: 'New License', waitMinutes: 165, isAnomaly: true, createdAt: Date.now() - 90 * 60 * 1000 },
    ],
  },
  {
    id: 'demo-3',
    name: 'LTO Novaliches District',
    address: 'Robinsons Novaliches, QC',
    city: 'Quezon City, NCR',
    lat: 14.7199,
    lng: 121.0289,
    distanceKm: 7.8,
    operatingHours: '08:00–17:00',
    thumbnailUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDIVd2lrAYL1Qg54Pz7-Gt_TOD2GBPDKEIlDtl15TZEzlsW7sVg8EffwaNrQ-Uv7cS_mGrtChEILO-Siksfzkfm0FrUvUbi7j8CYMPV7-hYQxPi4ue_FPNgvNvMEj9kxIy0grVPAyj5ccUq0XegMJ0RH6G-kNM_D_OhMLMsDWrqulPE02c6MFePG_iymv38Ra69HV2wIJro8o6RTcyNYJh_XXSLGOUcGhyNlXI-EBkNmFsodhnj0N47lMbKQX6p3J520QdeyLJow7iG',
    hasPlasticCards: false,
    grade: 'B',
    reportsToday: 18,
    is_puno: false,
    hasActiveAnomaly: false,
    walkinAvgMinutes: 100,
    appointmentAvgMinutes: 20,
    prequeueMinutesBeforeOpen: 20,
    communityRequirements7d: [],
    high_demand_warning: false,
    intentDistancesKmLast15m: [],
    plastic_uncertain: false,
    historical_puno_risk: false,
    recentReports: [
      { id: 'dr5', queuePrefix: 'N', transactionType: 'License Renewal', waitMinutes: 105, isAnomaly: false, createdAt: Date.now() - 18 * 60 * 1000 },
      { id: 'dr6', queuePrefix: 'N', transactionType: 'MV Registration', waitMinutes: 95, isAnomaly: false, createdAt: Date.now() - 65 * 60 * 1000 },
    ],
  },
];

// Backward-compatibility alias for existing imports
export const demoBranches = DEMO_BRANCHES;
